name: docker-cloudflare-vite-react-template

services:
  worker: &worker
    image: node:24-slim
    user: "${UID:-1000}:${GID:-1000}"
    command: [ "npm", "run", "vite-dev" ]
    working_dir: /app
    security_opt:
      - no-new-privileges:true
    ports:
      - "${HOST_PORT:-8789}:8787"
      - "${HOST_PREVIEW_PORT:-4175}:4173"
    environment:
      WRANGLER_SEND_METRICS: false
      NPM_CONFIG_UPDATE_NOTIFIER: false
    env_file:
      - .env.dev
    volumes:
      - .:/app

  preview:
    <<: *worker
    command: [ "npm", "run", "vite-preview" ]
